version: '3.1'

services:
  web:
    container_name: web
    hostname: web
    build:
      dockerfile: Homework/Dockerfile
      context: ..
    restart: "always"
    depends_on:
      - mysql
      - tarantool
      - kafka
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
    ports:
      - 80:80

  #web2:
  #  container_name: web2
  #  hostname: web2
  #  build:
  #    dockerfile: Homework/Dockerfile
  #    context: ..
  #  restart: "always"
  #  depends_on:
  #    - mysql
  #    - tarantool
  #    - kafka
  #    - dialogs-db1
  #    - dialogs-db2
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Compose
  #  ports:
  #    - 82:80

  dialogs_1:
    container_name: dialogs_1
    hostname: dialogs_1
    build:
      dockerfile: Dialogs/Dockerfile
      context: ..
    image: homework_dialogs:version
    restart: "always"
    depends_on:
      - dialogs-db1
      - dialogs-db2
      - kafka
      - consul
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose

  #dialogs_2:
  #  container_name: dialogs_2
  #  hostname: dialogs_2
  #  image: homework_dialogs:version
  #  restart: "always"
  #  depends_on:
  #    - dialogs-db1
  #    - dialogs-db2
  #    - kafka
  #    - consul
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Compose
  
  consul:
    container_name: consul
    hostname: consul
    image: consul
    ports:
      - 8500:8500

  usercounters:
    container_name: usercounters
    hostname: usercounters
    build:
      dockerfile: UserCounters/Dockerfile
      context: ..
    restart: "always"
    depends_on:
      - redis
      - kafka
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data:/var/lib/mysql
      - ./compose/master.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/homework_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  #mysql-slave1:
  #  depends_on:
  #    - mysql
  #  container_name: mysql-slave1
  #  hostname: mysql-slave1
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  cap_add:
  #    - SYS_NICE
  #  restart: "always"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example
  #  volumes:
  #    - homework_data_slave1:/var/lib/mysql
  #    - ./compose/slave1.cnf:/etc/mysql/conf.d/mysql.cnf
  #    - ./compose/slave.sql:/docker-entrypoint-initdb.d/00-slave.sql
  #  ports:
  #    - "3307:3306"

  #mysql-slave2:
  #  depends_on:
  #    - mysql
  #  container_name: mysql-slave2
  #  hostname: mysql-slave2
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  cap_add:
  #    - SYS_NICE
  #  restart: "always"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example
  #  volumes:
  #    - homework_data_slave2:/var/lib/mysql
  #    - ./compose/slave2.cnf:/etc/mysql/conf.d/mysql.cnf
  #    - ./compose/slave.sql:/docker-entrypoint-initdb.d/00-slave.sql
  #  ports:
  #    - "3308:3306"

  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    hostname: tarantool
    restart: "always"
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./compose/tarantool_lua:/opt/tarantool
    ports:
      - "3301:3301"
    command: tarantool /opt/tarantool/config.lua

  kafka:
    depends_on:
      - zookeeper
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: "always"
    hostname: kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
    - kafka:/bitnami/kafka
    ports:
      - "19092:19092"

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    restart: "always"
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - "zookeeper_data:/bitnami"

  dialogs-db1:
    container_name: dialogs-db1
    hostname: dialogs-db1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dialogs-db1_data:/var/lib/mysql
      - ./compose/dialogs_db:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"

  dialogs-db2:
    container_name: dialogs-db2
    hostname: dialogs-db2
    restart: "always"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dialogs-db2_data:/var/lib/mysql
      - ./compose/dialogs_db:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"
  
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: "always"
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  #haproxy:
  #  container_name: haproxy
  #  hostname: haproxy
  #  restart: "always"
  #  image: haproxy
  #  ports:
  #    - 8404:8404
  #  volumes:
  #    - ./compose/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  #nginx:
  #  container_name: nginx
  #  hostname: nginx
  #  restart: "always"
  #  image: nginx
  #  ports:
  #    - 80:80
  #  volumes:
  #    - ./compose/nginx.conf:/etc/nginx/nginx.conf

  redis:
    container_name: redis
    hostname: redis
    restart: "always"
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  #jaeger:
  #  container_name: jaeger
  #  hostname: jaeger
  #  restart: "always"
  #  image: jaegertracing/all-in-one
  #  ports:
  #    - 6831:6831
  #    - 16686:16686
  #  command: --memory.max-traces=1000

  #dialogs-db3:
  #  container_name: dialogs-db3
  #  hostname: dialogs-db3
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  cap_add:
  #    - SYS_NICE
  #  restart: "no"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example
  #  volumes:
  #    - dialogs-db3_data:/var/lib/mysql
  #    - ./compose/dialogs_db:/docker-entrypoint-initdb.d
  #  ports:
  #    - "3311:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./compose/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: "always"
    ports:
      - "9090:9090"

  grafana:
   image: grafana/grafana:latest
   container_name: grafana
   volumes:
     - grafana_data:/var/lib/grafana
   environment:
     - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
     - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
     - GF_USERS_ALLOW_SIGN_UP=false
   restart: "always"
   ports:
     - 3000:3000

  zabbix-mysql:
    container_name: zabbix-mysql
    hostname: zabbix-mysql
    image: mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    restart: "always"
    environment:
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: zabbix
    volumes:
      - zabbix_data:/var/lib/mysql

  zabbix:
    container_name: zabbix
    hostname: zabbix
    image: zabbix/zabbix-server-mysql
    restart: "always"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example

  zabbix-web:
    container_name: zabbix-web
    hostname: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql
    restart: "always"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - zabbix_data:/var/lib/mysql
    ports:
      - 8080:8080

  zabbix-agent:
    container_name:  zabbix-agent
    hostname:  zabbix-agent
    image: zabbix/zabbix-agent
    restart: "always"
    environment:
      ZBX_HOSTNAME: zabbix
      ZBX_SERVER_HOST: zabbix
    volumes:
      - zabbix_data:/var/lib/mysql
    privileged: true

volumes:
  homework_data:
  #homework_data_slave1:
  #homework_data_slave2:
  tarantool_data:
  #replicator_data:
  kafka:
  zookeeper_data:
  dialogs-db1_data:
  dialogs-db2_data:
  #dialogs-db3_data:
  redis_data:
  prometheus_data:
  grafana_data:
  zabbix_data: