version: '3.1'

services:
  web:
    container_name: web
    hostname: web
    build:
      dockerfile: Homework/Dockerfile
      context: ..
    restart: "always"
    depends_on:
      - mysql
      - tarantool
      - kafka
      - dialogs-db1
      - dialogs-db2
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
    ports:
      - 80:80

  #web2:
  #  container_name: web2
  #  hostname: web2
  #  build:
  #    dockerfile: Homework/Dockerfile
  #    context: ..
  #  restart: "always"
  #  depends_on:
  #    - mysql
  #    - tarantool
  #    - kafka
  #    - dialogs-db1
  #    - dialogs-db2
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Compose
  #  ports:
  #    - 82:80

  dialogs:
    container_name: dialogs
    hostname: dialogs
    build:
      dockerfile: Dialogs/Dockerfile
      context: ..
    restart: "always"
    depends_on:
      - dialogs-db1
      - dialogs-db2
      - kafka
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose

  usercounters:
    container_name: usercounters
    hostname: usercounters
    build:
      dockerfile: UserCounters/Dockerfile
      context: ..
    restart: "always"
    depends_on:
      - redis
      - kafka
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data:/var/lib/mysql
      - ./compose/master.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/master.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3306:3306"

  mysql-slave1:
    depends_on:
      - mysql
    container_name: mysql-slave1
    hostname: mysql-slave1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data_slave1:/var/lib/mysql
      - ./compose/slave1.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/slave.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3307:3306"

  mysql-slave2:
    depends_on:
      - mysql
    container_name: mysql-slave2
    hostname: mysql-slave2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data_slave2:/var/lib/mysql
      - ./compose/slave2.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/slave.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3308:3306"

  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    hostname: tarantool
    restart: "always"
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./compose/tarantool_lua:/opt/tarantool
    ports:
      - "3301:3301"
    command: tarantool /opt/tarantool/config.lua

  #replicator:
  #  image: replicator
  #  depends_on:
  #    - mysql
  #    - tarantool
  #  container_name: replicator
  #  hostname: replicator
  #  privileged: true
  #  volumes:
  #    - replicator_data:/home/replicator
  #    - D:/tarantool_replication:/home/replicator_share

  kafka:
    depends_on:
      - zookeeper
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: "always"
    hostname: kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
    - kafka:/bitnami/kafka
    ports:
      - "19092:19092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic user_dialog --describe"]
      interval: 2s
      timeout: 2s
      retries: 15

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    restart: "always"
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - "zookeeper_data:/bitnami"

  dialogs-db1:
    container_name: dialogs-db1
    hostname: dialogs-db1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dialogs-db1_data:/var/lib/mysql
      - ./compose/dialogs_db:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"

  dialogs-db2:
    container_name: dialogs-db2
    hostname: dialogs-db2
    restart: "always"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dialogs-db2_data:/var/lib/mysql
      - ./compose/dialogs_db:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"
  
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: "always"
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  haproxy:
    container_name: haproxy
    hostname: haproxy
    restart: "always"
    image: haproxy
    ports:
      - 8404:8404
    volumes:
      - ./compose/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  #nginx:
  #  container_name: nginx
  #  hostname: nginx
  #  restart: "always"
  #  image: nginx
  #  ports:
  #    - 80:80
  #  volumes:
  #    - ./compose/nginx.conf:/etc/nginx/nginx.conf

  redis:
    container_name: redis
    hostname: redis
    restart: "always"
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  #jaeger:
  #  container_name: jaeger
  #  hostname: jaeger
  #  restart: "always"
  #  image: jaegertracing/all-in-one
  #  ports:
  #    - 6831:6831
  #    - 16686:16686
  #  command: --memory.max-traces=1000

  #dialogs-db3:
  #  container_name: dialogs-db3
  #  hostname: dialogs-db3
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  cap_add:
  #    - SYS_NICE
  #  restart: "no"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example
  #  volumes:
  #    - dialogs-db3_data:/var/lib/mysql
  #    - ./compose/dialogs_db:/docker-entrypoint-initdb.d
  #  ports:
  #    - "3311:3306"

volumes:
  homework_data:
  homework_data_slave1:
  homework_data_slave2:
  tarantool_data:
  replicator_data:
  kafka:
  zookeeper_data:
  dialogs-db1_data:
  dialogs-db2_data:
  dialogs-db3_data:
  redis_data: