version: '3.1'

services:
  web:
    build:
      dockerfile: Homework/Dockerfile
      context: ..
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data:/var/lib/mysql
      - ./compose/master.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/master.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3306:3306"

  mysql-slave1:
    depends_on:
      - mysql
    container_name: mysql-slave1
    hostname: mysql-slave1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data_slave1:/var/lib/mysql
      - ./compose/slave1.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/slave.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3307:3306"

  mysql-slave2:
    depends_on:
      - mysql
    container_name: mysql-slave2
    hostname: mysql-slave2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data_slave2:/var/lib/mysql
      - ./compose/slave2.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./compose/slave.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3308:3306"

volumes:
  homework_data:
  homework_data_slave1:
  homework_data_slave2: