version: '3.1'

services:
  web:
    build: .
    ports:
      - "5000:5000"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - homework_data:/var/lib/mysql
        
volumes:
  homework_data: